// Code generated by goctl. DO NOT EDIT.
package types

type ClassAbsenceNotificationListReq struct {
}

type ClassAbsenceNotificationListResp struct {
}

type ClassAddReq struct {
	ID             int64   `json:"id"`              // 班级ID
	CampusID       int64   `json:"campus_id"`       // 校区ID
	CourseID       int64   `json:"course_id"`       // 课程ID
	ClassType      string  `json:"class_type"`      // 班级类型
	TeacherIDs     []int64 `json:"teacher_ids"`     // 教师ID列表
	AssistantIDs   []int64 `json:"assistant_ids"`   // 助教ID列表
	StartDate      int64   `json:"start_date"`      // 开课时间
	ClassTime      string  `json:"class_time"`      // 节课时间
	CourseDuration int32   `json:"course_duration"` // 课程总课时
	ClassDuration  int32   `json:"class_duration"`  // 班级课时
	Schedule       string  `json:"schedule"`        // 上课时间安排
	Status         string  `json:"status"`          // 班级状态
	Notes          string  `json:"notes"`           // 备注
	CreatedAt      int64   `json:"created_at"`      // 创建时间
	UpdatedAt      int64   `json:"updated_at"`      // 更新时间
}

type ClassAddResp struct {
}

type ClassAttendanceRecordAddReq struct {
}

type ClassAttendanceRecordAddResp struct {
}

type ClassAttendanceRecordDeleteReq struct {
}

type ClassAttendanceRecordDeleteResp struct {
}

type ClassAttendanceRecordInfoReq struct {
}

type ClassAttendanceRecordInfoResp struct {
}

type ClassAttendanceRecordListReq struct {
}

type ClassAttendanceRecordListResp struct {
}

type ClassAttendanceRecordModifyReq struct {
}

type ClassAttendanceRecordModifyResp struct {
}

type ClassAttendanceRecordTimeoutListReq struct {
}

type ClassAttendanceRecordTimeoutListResp struct {
}

type ClassDeleteReq struct {
}

type ClassDeleteResp struct {
}

type ClassInfoReq struct {
}

type ClassInfoResp struct {
}

type ClassListReq struct {
}

type ClassListResp struct {
}

type ClassModifyReq struct {
}

type ClassModifyResp struct {
}

type ClassScheduleAddReq struct {
	ID             int64  `json:"id"`              // 班级ID（假设有一个唯一标识符）
	Name           string `json:"name"`            // 班级名称
	Status         string `json:"status"`          // 状态（如"未上课"）
	CourseCategory string `json:"course_category"` // 课程类别
	StartTime      int64  `json:"start_time"`      // 上课时间（Unix时间戳）
	Duration       string `json:"duration"`        // 上课时长
	Content        string `json:"content"`         // 上课内容
	Teacher        string `json:"teacher"`         // 上课老师
	TeachingMethod string `json:"teaching_method"` // 上课方式（如"线下"）
	Location       string `json:"location"`        // 上课地址
	AttendanceRate string `json:"attendance_rate"` // 出勤率
	CourseType     string `json:"course_type"`     // 课程类型
	StudentCount   int    `json:"student_count"`   // 本班人数
	Notes          string `json:"notes"`           // 备注
	CreatedAt      int64  `json:"created_at"`      // 创建时间（Unix时间戳）
	UpdatedAt      int64  `json:"updated_at"`      // 更新时间（Unix时间戳）
}

type ClassScheduleAddResp struct {
}

type ClassScheduleDeleteReq struct {
}

type ClassScheduleDeleteResp struct {
}

type ClassScheduleInfoReq struct {
}

type ClassScheduleInfoResp struct {
}

type ClassScheduleListReq struct {
}

type ClassScheduleListResp struct {
}

type ClassScheduleModifyReq struct {
}

type ClassScheduleModifyResp struct {
}

type ClassScheduleStopReq struct {
}

type ClassScheduleStopResp struct {
}

type ClassStopReq struct {
}

type ClassStopResp struct {
}

type Contact struct {
	PhoneNumber  string `json:"phone_number,optional"`                                // 联系人手机号
	Type         int64  `json:"type" validate:"required,max=10" required:"联系人类型不能为空"` // 联系人类型
	Relationship string `json:"relationship,optional"`                                // 与学生的关系
	Name         string `json:"name,optional"`                                        // 联系人姓名
	WechatId     string `json:"wechat_id,optional"`                                   // 联系人微信号
}

type CourseAddReq struct {
	OrderNumber       string  `json:"order_number"`       //订单id
	CourseName        string  `json:"course_name"`        //课程名称
	CourseDescription string  `json:"course_description"` //课程描述
	Source            string  `json:"source"`             //课程来源
	CreatedAt         int64   `json:"created_at"`         //创建时间
	UpdatedAt         int64   `json:"updated_at"`         //更新时间
	Status            string  `json:"status"`             //课程状态值
	TotalAmount       float64 `json:"total_amount"`       //总价
	CourseHours       int32   `json:"course_hours"`       //课程时长
	CustomerID        int64   `json:"customer_id"`        //客户id
	ValidFrom         int64   `json:"valid_from"`         //有效期开始时间
	ValidUntil        int64   `json:"valid_until"`        //有效期结束时间
	IsSpecialClass    bool    `json:"is_special_class"`   //是否为专班课程
	SpecialClassID    int64   `json:"special_class_id"`   //特殊课程id
	SourceOrderID     int64   `json:"source_order_id"`    //源订单id
}

type CourseAddResp struct {
}

type CourseDeleteReq struct {
}

type CourseDeleteResp struct {
}

type CourseEnrollmentSituationResp struct {
}

type CourseInfoReq struct {
}

type CourseInfoResp struct {
}

type CourseListReq struct {
}

type CourseListResp struct {
}

type CourseModifyReq struct {
	Name         string   `json:"name"`          // 课程名称
	Category     string   `json:"category"`      // 课程类别
	QuestionBank string   `json:"question_bank"` // 关联题库
	Type         string   `json:"type"`          // 课程类型（班课/定制课）
	Price        float64  `json:"price"`         // 课程价格
	Duration     float64  `json:"duration"`      // 课时（小时）
	HourlyRate   float64  `json:"hourly_rate"`   // 课时单价
	Contents     []string `json:"contents"`      // 上课内容
	Description  string   `json:"description"`   // 课程介绍
	CreatedAt    int64    `json:"created_at"`    // 创建时间（Unix时间戳）
	UpdatedAt    int64    `json:"updated_at"`    // 更新时间（Unix时间戳）
}

type CourseModifyResp struct {
}

type CourseStopReq struct {
}

type CourseStopResp struct {
}

type CourseenrollmentsituationReq struct {
}

type CustomerAddReq struct {
}

type CustomerAddResp struct {
}

type CustomerDeleteReq struct {
}

type CustomerDeleteResp struct {
}

type CustomerInfoReq struct {
}

type CustomerInfoResp struct {
}

type CustomerListReq struct {
}

type CustomerListResp struct {
}

type CustomerModifyReq struct {
}

type CustomerModifyResp struct {
}

type CustomerRelationshipAddReq struct {
}

type CustomerRelationshipAddResp struct {
}

type CustomerRelationshipDeleteReq struct {
}

type CustomerRelationshipDeleteResp struct {
}

type CustomerRelationshipGroupAddReq struct {
}

type CustomerRelationshipGroupAddResp struct {
}

type CustomerRelationshipGroupDeleteReq struct {
}

type CustomerRelationshipGroupDeleteResp struct {
}

type CustomerRelationshipGroupInfoReq struct {
}

type CustomerRelationshipGroupInfoResp struct {
}

type CustomerRelationshipGroupListReq struct {
}

type CustomerRelationshipGroupListResp struct {
}

type CustomerRelationshipGroupModifyReq struct {
}

type CustomerRelationshipGroupModifyResp struct {
}

type CustomerRelationshipInfoReq struct {
}

type CustomerRelationshipInfoResp struct {
}

type CustomerRelationshipListReq struct {
}

type CustomerRelationshipListResp struct {
}

type CustomerRelationshipModifyReq struct {
}

type CustomerRelationshipModifyResp struct {
}

type CustomerStopReq struct {
}

type CustomerStopResp struct {
}

type ErrorInfo struct {
	ErrorCode int64  `json:"errno"`
	ErrorMsg  string `json:"error"`
}

type ErrorResponse struct {
	ErrorInfo ErrorInfo `json:"error_info"`
}

type LearningGoal struct {
	TargetScore   float64 `json:"target_score,optional"`   // 目标分数
	EntryScore    float64 `json:"entry_score,optional"`    // 入学分数
	TargetCourse  string  `json:"target_course,optional"`  // 咨询课程
	TargetCountry string  `json:"target_country,optional"` // 目标国家
}

type NoticeManageAddReq struct {
}

type NoticeManageAddResp struct {
}

type NoticeManageDeleteReq struct {
}

type NoticeManageDeleteResp struct {
}

type NoticeManageEnrollmentSituationResp struct {
}

type NoticeManageInfoReq struct {
}

type NoticeManageInfoResp struct {
}

type NoticeManageListReq struct {
}

type NoticeManageListResp struct {
}

type NoticeManageModifyReq struct {
}

type NoticeManageModifyResp struct {
}

type NoticeManageStopReq struct {
}

type NoticeManageStopResp struct {
}

type NoticeManageenrollmentsituationReq struct {
}

type OrderListReq struct {
}

type OrderListResp struct {
}

type ParentAccount struct {
	Name          string `json:"name,optional"`           // 家长姓名
	Relationship  string `json:"relationship,optional"`   // 与学生的关系
	PhoneNumber   string `json:"phone_number,optional"`   // 家长手机号
	LoginPassword string `json:"login_password,optional"` // 家长登录密码
}

type QwTokenResp struct {
	ErrCode     int64  `json:"errcode"`
	ErrMsg      string `json:"errmsg"`
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
}

type QwUserIdByEmailReq struct {
	Email     string `json:"email"`
	EmailType int64  `json:"email_type"`
}

type QwUserIdByMobileReq struct {
	Mobile string `json:"mobile"`
}

type QwUserIdResp struct {
	ErrCode int64  `json:"errcode"`
	Errmsg  string `json:"errmsg"`
	Userid  string `json:"userid"`
}

type SalarySettlementReq struct {
}

type SalarySettlementResp struct {
}

type StudentAddReq struct {
	Name           string          `json:"name" validate:"required"`                     // 姓名
	Gender         int64           `json:"gender"`                                       // 性别（男/女）
	DateOfBirth    int64           `json:"date_of_birth,optional"`                       // 出生日期（Unix时间戳）
	City           string          `json:"city" validate:"required" required:"所在城市不能为空"` // 所在城市
	PhoneNumber    string          `json:"phone_number,optional"`                        // 手机号
	Major          string          `json:"major,optional"`                               // 专业
	WechatId       string          `json:"wechat_id,optional"`                           // 微信号
	WechatNickname string          `json:"wechat_nickname,optional"`                     // 微信昵称
	School         string          `json:"school,optional"`                              // 学校
	Grade          string          `json:"grade,optional"`                               // 年级
	Contacts       []Contact       `json:"contacts,optional" validate:"dive"`            // 主要联系人信息
	StudentType    int64           `json:"student_type,optional"`                        // 学生属性（新生/老生）
	LearningGoals  []LearningGoal  `json:"learning_goals,optional"`                      // 学生目标列表
	Notes          string          `json:"notes,optional"`                               // 备注
	AccountType    int64           `json:"account_type,optional"`                        // 账号类型（VIP/非VIP）
	LoginPassword  string          `json:"login_password,optional"`                      // 登录密码
	Subscription   string          `json:"subscription,optional"`                        // 套餐选择（例如："12个月/剩余数量: 10"）
	ParentAccounts []ParentAccount `json:"parent_accounts,optional"`                     // 家长账号信息
	CreatedAt      int64           `json:"created_at,optional"`                          // 创建时间（Unix时间戳）
	UpdatedAt      int64           `json:"updated_at,optional"`                          // 更新时间（Unix时间戳）
}

type StudentAddResp struct {
}

type StudentDeleteReq struct {
}

type StudentDeleteResp struct {
}

type StudentEnrollmentSituationResp struct {
}

type StudentInfoReq struct {
}

type StudentInfoResp struct {
}

type StudentListReq struct {
}

type StudentListResp struct {
}

type StudentModifyReq struct {
}

type StudentModifyResp struct {
}

type StudentScheduleAddReq struct {
}

type StudentScheduleAddResp struct {
}

type StudentScheduleDeleteReq struct {
}

type StudentScheduleDeleteResp struct {
}

type StudentScheduleInfoReq struct {
}

type StudentScheduleInfoResp struct {
}

type StudentScheduleListReq struct {
}

type StudentScheduleListResp struct {
}

type StudentScheduleModifyReq struct {
}

type StudentScheduleModifyResp struct {
}

type StudentScheduleStopReq struct {
}

type StudentScheduleStopResp struct {
}

type StudentStopReq struct {
}

type StudentStopResp struct {
}

type StudentenrollmentsituationReq struct {
}

type TeacherAddReq struct {
}

type TeacherAddResp struct {
}

type TeacherDeleteReq struct {
}

type TeacherDeleteResp struct {
}

type TeacherEnrollmentSituationResp struct {
}

type TeacherInfoReq struct {
}

type TeacherInfoResp struct {
}

type TeacherListReq struct {
}

type TeacherListResp struct {
}

type TeacherModifyReq struct {
}

type TeacherModifyResp struct {
}

type TeacherScheduleAddReq struct {
}

type TeacherScheduleAddResp struct {
}

type TeacherScheduleDeleteReq struct {
}

type TeacherScheduleDeleteResp struct {
}

type TeacherScheduleInfoReq struct {
}

type TeacherScheduleInfoResp struct {
}

type TeacherScheduleListReq struct {
}

type TeacherScheduleListResp struct {
}

type TeacherScheduleModifyReq struct {
}

type TeacherScheduleModifyResp struct {
}

type TeacherScheduleStopReq struct {
}

type TeacherScheduleStopResp struct {
}

type TeacherStopReq struct {
}

type TeacherStopResp struct {
}

type TeacherenrollmentsituationReq struct {
}

type TimeScheduleAddReq struct {
}

type TimeScheduleAddResp struct {
}

type TimeScheduleDeleteReq struct {
}

type TimeScheduleDeleteResp struct {
}

type TimeScheduleInfoReq struct {
}

type TimeScheduleInfoResp struct {
}

type TimeScheduleListReq struct {
}

type TimeScheduleListResp struct {
}

type TimeScheduleModifyReq struct {
}

type TimeScheduleModifyResp struct {
}

type TimeScheduleStopReq struct {
}

type TimeScheduleStopResp struct {
}

type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type LeaveapplicationListReq struct {
}

type LeaveapplicationListResp struct {
}

type NotificationAddReq struct {
}

type NotificationAddResp struct {
}

type NotificationDeleteReq struct {
}

type NotificationDeleteResp struct {
}

type NotificationEnrollmentSituationResp struct {
}

type NotificationInfoReq struct {
}

type NotificationInfoResp struct {
}

type NotificationListReq struct {
}

type NotificationListResp struct {
}

type NotificationModifyReq struct {
}

type NotificationModifyResp struct {
}

type NotificationStopReq struct {
}

type NotificationStopResp struct {
}

type NotificationenrollmentsituationReq struct {
}
